### ISSUE TITLE
No-go polyline sometimes leaky

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#288] opened 2021-01-28 09:39 UTC
BRouter-Web has a new feature to add an allowed zone as a circle or boundary to help with complying to Corona mobility restrictions. Examples are [Dresden (15 km radius)](https://brouter.de/brouter-web/?lng=de-DE#map=12/51.1177/13.5794/standard&lonlats=13.482274,51.152634;13.484784,51.154135&ringgo=13.587642,51.042001,15000) and [Konstanz (boundary + 15 km buffer)](https://brouter.de/brouter-web/#map=11/47.7069/9.0984/standard&lonlats=8.933135,47.650682;8.933795,47.659807&ringgo=9.168777,47.665619,15000&profile=trekking-noferries) (just as example, rule does not apply in BW), both routes can't go over nearby, outside bridge. 

@bagage had the idea to implement such a radius limit with a no-go polyline as a closed ring. The expectation is that a route always stays within the ring and that it throws an error (400 - no track found) when one route point is outside the ring (clicking outside is suppressed, but you can still drag a marker out).

But sometimes the route finds a way through the no-go polyline.

A minimal example I found is this:
- [Berlin (closed ring with 6 points)](https://brouter.de/brouter-web/#map=13/52.5154/13.3837/standard&lonlats=13.328347,52.503267;13.307748,52.500157&polylines=13.387184,52.561973,13.313373,52.517034,13.319018,52.499849,13.33503,52.485285,13.387184,52.472141,13.460995,52.517034,13.387184,52.561973)
  - (derived from a [5 km radius circle with 16 points](https://brouter.de/brouter-web/#map=12/52.5160/13.4304/standard&lonlats=13.328347,52.503267;13.307748,52.500157&polylines=13.387184,52.561973,13.358911,52.55855,13.334954,52.548806,13.318965,52.534226,13.313373,52.517034,13.319018,52.499849,13.33503,52.485285,13.358964,52.475557,13.387184,52.472141,13.415404,52.475557,13.439338,52.485285,13.45535,52.499849,13.460995,52.517034,13.455403,52.534226,13.439414,52.548806,13.415457,52.55855,13.387184,52.561973) by deleting points)

But leaks not only happen with closed rings, above route also goes through this [opened polyline](https://brouter.de/brouter-web/#map=13/52.5341/13.3878/standard&lonlats=13.328347,52.503267;13.307748,52.500157&polylines=13.463745,52.577393,13.31543,52.508488,13.319018,52.499849,13.327274,52.492503,13.497734,52.565917) instead of going around. Lines can be clicked to edit, so you can play around.

More leak examples:
- [Paris (20 km circle)](https://brouter.de/brouter-web/#map=11/48.9294/2.5303/standard&lonlats=2.617321,48.892824;2.63217,48.890597&polylines=2.361374,49.119754,2.334468,49.118886,2.307823,49.11629,2.2817,49.11199,2.256352,49.10603,2.232025,49.098468,2.208956,49.089375,2.187369,49.078842,2.167471,49.06697,2.149454,49.053874,2.133493,49.039682,2.119739,49.024532,2.108324,49.008569,2.099356,48.991948,2.092919,48.97483,2.089073,48.957381,2.087852,48.939768,2.089265,48.922161,2.093296,48.90473,2.099903,48.887642,2.10902,48.871061,2.120557,48.855147,2.134402,48.840053,2.15042,48.825921,2.168455,48.812889,2.188334,48.80108,2.209866,48.790607,2.232844,48.781571,2.257048,48.774057,2.282247,48.768137,2.3082,48.763868,2.33466,48.76129,2.361374,48.760428,2.388088,48.76129,2.414548,48.763868,2.440501,48.768137,2.4657,48.774057,2.489904,48.781571,2.512882,48.790607,2.534414,48.80108,2.554293,48.812889,2.572328,48.825921,2.588346,48.840053,2.602191,48.855147,2.613728,48.871061,2.622845,48.887642,2.629452,48.90473,2.633483,48.922161,2.634896,48.939768,2.633675,48.957381,2.629829,48.97483,2.623392,48.991948,2.614424,49.008569,2.603009,49.024532,2.589255,49.039682,2.573294,49.053874,2.555277,49.06697,2.535379,49.078842,2.513792,49.089375,2.490723,49.098468,2.466396,49.10603,2.441048,49.11199,2.414925,49.11629,2.38828,49.118886,2.361374,49.119754)
- [Essen (boundary + 15 km)](https://brouter.de/brouter-web/#map=11/51.3398/7.1397/standard&lonlats=7.288131,51.297645;7.298194,51.297504&polylines=6.679193,51.485046,6.678131,51.468543,6.678143,51.468409,6.683988,51.449868,6.68237,51.449676,6.682414,51.449534,6.686585,51.438437,6.686695,51.438193,6.688716,51.43486,6.689398,51.432695,6.690183,51.431261,6.690816,51.431396,6.700301,51.415746,6.702171,51.413798,6.70143,51.412834,6.690785,51.384997,6.689796,51.356386,6.69849,51.328287,6.716459,51.301965,6.716794,51.301589,6.736343,51.283361,6.738299,51.281823,6.738426,51.281733,6.739316,51.280775,6.76383,51.259489,6.794442,51.241566,6.829995,51.227681,6.869151,51.218356,6.888011,51.21634,6.905433,51.214061,6.909681,51.214021,6.910439,51.213939,6.913348,51.213986,6.942396,51.213704,6.955311,51.21272,6.965309,51.21315,6.974892,51.212882,6.989135,51.214171,6.996011,51.214465,7.000391,51.215188,7.014927,51.2165,7.053188,51.22473,7.055957,51.225514,7.063231,51.227791,7.063358,51.227813,7.073759,51.227893,7.074708,51.227946,7.07641,51.228156,7.076932,51.228191,7.076927,51.22822,7.11952,51.233476,7.1321,51.236867,7.151009,51.239067,7.160687,51.241545,7.173966,51.243865,7.174808,51.244062,7.204037,51.25252,7.207678,51.254021,7.216087,51.256054,7.255555,51.272548,7.262977,51.277416,7.265535,51.278631,7.279204,51.288056,7.28833,51.294036,7.289211,51.294952,7.29229,51.297073,7.313189,51.318273,7.327515,51.341511,7.33477,51.365997,7.334765,51.367502,7.343281,51.38028,7.343861,51.381955,7.344457,51.38285,7.349582,51.398451,7.351556,51.404141,7.351575,51.404516,7.352752,51.408096,7.353204,51.433866,7.353187,51.433925,7.353238,51.436198,7.349895,51.448115,7.349987,51.44947,7.343971,51.474736,7.330405,51.498841,7.32265,51.507142,7.320361,51.513225,7.307396,51.532949,7.306484,51.534073,7.287333,51.553419,7.282143,51.557094,7.282053,51.557185,7.281156,51.557975,7.280979,51.55813,7.280758,51.558324,7.278847,51.559718,7.273898,51.563537,7.271862,51.56505,7.271674,51.564953,7.255711,51.576595,7.255416,51.576775,7.235023,51.587744,7.234953,51.587777,7.225216,51.59175,7.199347,51.610121,7.175736,51.621553,7.165617,51.628989,7.133371,51.645116,7.09676,51.657144,7.09667,51.657167,7.068321,51.6627,7.061914,51.664287,7.055163,51.664936,7.053872,51.665113,7.053853,51.665062,7.013459,51.668936,7.011242,51.668991,6.982801,51.668542,6.982341,51.668516,6.965802,51.667179,6.963915,51.666981,6.939177,51.663442,6.937986,51.663225,6.898307,51.653278,6.86256,51.638691,6.853403,51.633079,6.852342,51.632596,6.850707,51.63169,6.84515,51.628018,6.832133,51.620033,6.832007,51.619939,6.832006,51.619938,6.830706,51.619666,6.794564,51.606911,6.778587,51.598401,6.759755,51.590103,6.729969,51.570331,6.72531,51.565618,6.724824,51.565278,6.721285,51.561547,6.707163,51.547254,6.706235,51.54567,6.703607,51.542897,6.700307,51.537086,6.695216,51.530906,6.694056,51.529076,6.69374,51.528585,6.691617,51.523263,6.689902,51.520969,6.679842,51.495119,6.679735,51.493461,6.679406,51.492635,6.679355,51.49233,6.678578,51.486594,6.678425,51.485076,6.679193,51.485046)

Our workaround is to split circles into two half arcs and boundaries into 62 km chunks (~ 20 km radius half arc length), which seems to prevent those leaks, at least I haven't found a counter example yet:

- [Berlin (closed ring with 6 points), split](https://brouter.de/brouter-web/#map=13/52.5154/13.3837/standard&lonlats=13.328347,52.503267;13.307748,52.500157&polylines=13.387184,52.561973,13.313373,52.517034,13.319018,52.499849,13.33503,52.485285,13.387184,52.472141;13.387184,52.472141,13.460995,52.517034,13.387184,52.561973)
- [Paris (20 km circle), split](https://brouter.de/brouter-web/#map=11/48.9294/2.5303/standard&lonlats=2.617321,48.892824;2.63217,48.890597&ringgo=2.361374,48.940091,20000)
- [Essen (boundary + 15 km), split](https://brouter.de/brouter-web/#map=11/51.3398/7.1397/standard&lonlats=7.288131,51.297645;7.298194,51.297504&ringgo=7.002411,51.460852,15000&polylines=6.679193,51.485046,6.678131,51.468543,6.678143,51.468409,6.683988,51.449868,6.68237,51.449676,6.682414,51.449534,6.686585,51.438437,6.686695,51.438193,6.688716,51.43486,6.689398,51.432695,6.690183,51.431261,6.690816,51.431396,6.700301,51.415746,6.702171,51.413798,6.70143,51.412834,6.690785,51.384997,6.689796,51.356386,6.69849,51.328287,6.716459,51.301965,6.716794,51.301589,6.736343,51.283361,6.738299,51.281823,6.738426,51.281733,6.739316,51.280775,6.76383,51.259489,6.794442,51.241566,6.829995,51.227681,6.869151,51.218356,6.888011,51.21634,6.905433,51.214061,6.909681,51.214021,6.910439,51.213939,6.913348,51.213986,6.942396,51.213704,6.955311,51.21272,6.965309,51.21315,6.974892,51.212882,6.989135,51.214171,6.996011,51.214465,7.000391,51.215188,7.014927,51.2165,7.053188,51.22473,7.055957,51.225514,7.063231,51.227791,7.063358,51.227813,7.073759,51.227893,7.074708,51.227946,7.07641,51.228156,7.076932,51.228191,7.076927,51.22822,7.11952,51.233476,7.1321,51.236867,7.151009,51.239067,7.160687,51.241545,7.173966,51.243865,7.174808,51.244062,7.204037,51.25252,7.207678,51.254021,7.216087,51.256054,7.231115,51.262337;7.231115,51.262337,7.255555,51.272548,7.262977,51.277416,7.265535,51.278631,7.279204,51.288056,7.28833,51.294036,7.289211,51.294952,7.29229,51.297073,7.313189,51.318273,7.327515,51.341511,7.33477,51.365997,7.334765,51.367502,7.343281,51.38028,7.343861,51.381955,7.344457,51.38285,7.349582,51.398451,7.351556,51.404141,7.351575,51.404516,7.352752,51.408096,7.353204,51.433866,7.353187,51.433925,7.353238,51.436198,7.349895,51.448115,7.349987,51.44947,7.343971,51.474736,7.330405,51.498841,7.32265,51.507142,7.320361,51.513225,7.307396,51.532949,7.306484,51.534073,7.287333,51.553419,7.282143,51.557094,7.282053,51.557185,7.281156,51.557975,7.280979,51.55813,7.280758,51.558324,7.278847,51.559718,7.273898,51.563537,7.271862,51.56505,7.271674,51.564953,7.255711,51.576595,7.255416,51.576775,7.235023,51.587744,7.234953,51.587777,7.225216,51.59175,7.199347,51.610121,7.175736,51.621553,7.165617,51.628989,7.133371,51.645116,7.09676,51.657144,7.09667,51.657167,7.068321,51.6627,7.061914,51.664287,7.055163,51.664936,7.053872,51.665113,7.053853,51.665062,7.013459,51.668936,7.011242,51.668991,6.982801,51.668542,6.982341,51.668516,6.979628,51.668297;6.979628,51.668297,6.965802,51.667179,6.963915,51.666981,6.939177,51.663442,6.937986,51.663225,6.898307,51.653278,6.86256,51.638691,6.853403,51.633079,6.852342,51.632596,6.850707,51.63169,6.84515,51.628018,6.832133,51.620033,6.832007,51.619939,6.832006,51.619938,6.830706,51.619666,6.794564,51.606911,6.778587,51.598401,6.759755,51.590103,6.729969,51.570331,6.72531,51.565618,6.724824,51.565278,6.721285,51.561547,6.707163,51.547254,6.706235,51.54567,6.703607,51.542897,6.700307,51.537086,6.695216,51.530906,6.694056,51.529076,6.69374,51.528585,6.691617,51.523263,6.689902,51.520969,6.679842,51.495119,6.679735,51.493461,6.679406,51.492635,6.679355,51.49233,6.678578,51.486594,6.678425,51.485076,6.679193,51.485046)

**Comment by ntruchsess** [comment] 2021-01-28 18:02
Interesting. The feature is out in the wild for two years now and nobody noticed :-)
Thanks for pointing that out with nice examples to reproduce.
I have a vague idea what causes it, but need to verify on my own install. To minimise the performance-impact the algorithm first calculates enclosing circles for each nogo-polygon. When searching for the best route it always does a quick check whether a way-segment intersects this enclosing circle or not. If it does all segments of the polygon need to be checked individually. If it does not intersect the enclosing circle the polygon is not taken into account for this step any more.
My idea is that if the endpoint of a way-segment, the polygon-segment's endpoint and the enclosing circle are very close to each other the numerical precision might with it's round-off effects might result in a way-segments endpoint will be numerically outside the enclosing circle while it would not pass the intersection-test with the polygon segment.

**Comment by ntruchsess** [comment] 2021-01-28 19:09
I just did reproduce on my own install and can verify my theory seems to be true. Removing the 'intersects enclosing circle'-check (RoutingContext line 368 'if ( radius > nogo.radius ) continue;') resolves the issue. I guess I can provide a PR with a more reasonable fix quite soon ;-)

**Comment by zod** [comment] 2021-11-21 06:35
@ntruchsess & @nrenner
It seems this issue was fixed by #289. Feel free to reopen if it still exists.

**Closed by zod** 2021-11-21 06:35 UTC
