### ISSUE TITLE
Highways under construction shouldn't be routed along

### ISSUE THREAD

**Issue by DerDings** [abrensch/brouter#284] opened 2021-01-08 19:55 UTC
Currently BRouter routes along highways which are not yet finished in construction and thus inaccessible:
 https://brouter.de/brouter-web/#map=14/51.4681/7.2653/standard,route-quality&lonlats=7.274194,51.470371;7.260525,51.464779

How the result should look:
 https://brouter.de/brouter-web/#map=14/51.4683/7.2646/standard,route-quality&lonlats=7.274194,51.470371;7.260525,51.464779&nogos=7.267574,51.46811,40

**Comment by stefanct** [comment] 2021-08-09 02:12
duplicate of #62.

**Closed** 2023-07-22 15:38 UTC
Labels: duplicate
