### ISSUE TITLE
"No right turn on red" relation is wrongly interpreted as a prohibited turn

### ISSUE THREAD

**Issue by tensleepslav25** [abrensch/brouter#572] opened 2023-06-23 04:25 UTC
A right turn from Cedar Street onto Worcester Street with a "no turn on red" sign (as seen in route link) is legal, however one must wait until the light turns green. I propose that `restriction=no_right_turn_on_red` and `restriction=no_left_turn_on_red` tags apply a standard traffic signal penalty, such as if the route were to continue straight.

[Route link](https://brouter.de/brouter-web/#map=18/42.31513/-71.24650/standard&lonlats=-71.246481,42.314959;-71.245901,42.315464&profile=car-eco)
[Relation link](https://www.openstreetmap.org/relation/15976035)

Edit: in the meantime, is there any way to customize the car-eco profile so that the above tags are simply ignored in terms of routing?

**Comment by abrensch** [comment] 2023-07-01 06:49
Hi tensleepslav25,

ja the preprocessor just looks for "only_" and "no_" prefixes from the restriction tag.

There seem to be competing approaches on how to map "on_red" restrictions: https://wiki.openstreetmap.org/wiki/No_turn_on_red

Sure I can filter out the "on_red" restrictions during pre-processing.

But there's no way to do it on the profile-level.

**Comment by tensleepslav25** [comment] 2023-07-01 21:58
Thanks for the reply.

Filtering out "on_red" in pre-processing seems like the most sensible solution given the lack of consensus on tagging.

**Comment by quaelnix** [comment] 2023-07-02 07:13
> in the meantime, is there any way to customize the car-eco profile so that the above tags are simply ignored in terms of routing?

But for some reason [it's already being ignored](https://brouter.de/brouter-web/#map=18/42.31513/-71.24650/standard&lonlats=-71.246481,42.314959;-71.245901,42.315464&profile=car-eco), isn't it?
![no_right_turn_on_red](https://github.com/abrensch/brouter/assets/122357328/d3c598f0-aee7-4381-ac7d-bf40cdcbca93)
While [this classic "no right turn" relation](https://brouter.de/brouter-web/#map=19/42.31254/-71.22133/standard&lonlats=-71.22134,42.312766;-71.221404,42.312719&profile=car-eco) is being respected:
![no_right_turn](https://github.com/abrensch/brouter/assets/122357328/7c44ce01-76ca-4e1d-866f-885b7a7fb5a0)

**Comment by quaelnix** [comment] 2023-07-02 07:22
The example mentioned in post #1 does not work for some reason. Here is one that does:

- [Route link](https://brouter.de/brouter-web/#map=19/42.36748/-71.09719/standard&lonlats=-71.09746,42.367735;-71.097145,42.367791&profile=car-eco)
- [Relation link](https://www.openstreetmap.org/relation/14995868)

**Comment by tensleepslav25** [comment] 2023-07-02 07:28
Ah, I removed the relation from the original example as that turn is one I frequently use for routing. Probably should have clarified that.

**Comment by quaelnix** [comment] 2023-07-02 08:27
I noticed the [remove "no turn on red" restriction until further notice](https://www.openstreetmap.org/changeset/137701298) changeset, but relation [15976035](https://www.openstreetmap.org/relation/15976035/history) still exists?

**Comment by quaelnix** [comment] 2023-07-02 08:30
What really catched me off guard is [that you "removed the relation" by removing the via member](https://www.openstreetmap.org/relation/15976035/history). ;-)

**Comment by Pengor** [comment] 2023-10-23 16:43
Hi, looks like this was fixed in 1a2bb19 and was included in version [1.7.1](https://github.com/abrensch/brouter/releases/tag/v1.7.1)? Should this issue be closed?

I happened upon this because this (former) limitation is mentioned in a couple of places on the OSM wiki:
https://wiki.openstreetmap.org/wiki/No_turn_on_red
https://wiki.openstreetmap.org/wiki/Tag:restriction%3Dno_right_turn_on_red
I'm happy to update those if the issue is indeed resolved.

**Comment by quaelnix** [comment] 2023-10-30 07:30
Yes, this problem has been fixed. Thanks for the reminder!

PS: For some reason brouter.de is still running an older version of BRouter that does not yet include this fix.

**Closed by quaelnix** 2023-10-30 07:30 UTC
Labels: bug
