### ISSUE TITLE
Add routing for trams

### ISSUE THREAD

**Issue by Dimitar5555** [abrensch/brouter#421] opened 2022-04-15 11:27 UTC
Is it possible to add routing for trams? It should work the same way that train routing works.

**Comment by polyscias** [comment] 2022-04-15 12:31
Yes, that is possible, just give it a try on [brouter-web](http://brouter.de/brouter-web), select the Rail profile and then edit the profile (press the T key) and change:
```
assign costfactor
  switch railway=rail 1
  switch railway=narrow_gauge 1
  100000
```
into:

```
assign costfactor
  switch railway=tram 1
  100000 
```
I think it will not give the best results always, I think you will be better off with something like https://github.com/geofabrik/OpenRailRouting

**Comment by zod** [comment] 2022-04-15 13:04
Duplicate of #409

**Closed** 2022-06-08 17:20 UTC
