### ISSUE TITLE
BRouter U-turn command missing.

### ISSUE THREAD

**Issue by 0709wiwiwi** [abrensch/brouter#436] opened 2022-05-24 14:37 UTC
Current: BRouter (web) does not generate U-turns.

Desired: Brouter (web) generates U-turns.

Generating U-turns (180° track returns) is very valuable. By generating U-turns you can avoid unclear or false turn indications.
Especially when navigating with "display off" and with TTS audio indication mainly, U-turns can prevent very serious wrong turn instructions. How the confusion can arise without those U-turns can be found in the link to the google BRouter discussion group.

Pse find the details here:
https://groups.google.com/g/osm-android-bikerouting/c/-ljF8nqbFZc/m/4CjP2PQ7AAAJ

**Comment by polyscias** [comment] 2022-05-24 16:58
I am not so sure u-turn instructions are the solutions for this problem.

The Via point is about 1 meter from the wanted route and I would think that by the default setting of turnInstructionCatchingRange=40 (meter) this 1 meter detour would be ignored completely and the only turn instruction should be "Turn left".

So there is a bug, I can recreate the bug using OsmAnd turn instructions, it gives _Turn Right_ and 85 degrees, that is clearly incorrect. I tried also with turnInstructionCatchingRange=0 but then I still get only only one instruction this time _Keep Right_ with 0 degrees also clearly wrong.

Looking at this issue this way is also linked to what was discussed in #332

**Comment by 0709wiwiwi** [comment] 2022-05-24 18:25
The simplification problem by turnInstructionCatchingRange=40 (meter)  was also presented here.
https://groups.google.com/g/osm-android-bikerouting/c/1zl5NSLR0y8
In my planning experiences this method is not a heaven on earth method.  On the contrary.
So this simplification tool should be used with of lot of care (or not) and by well understanding what really happens! 

And it does does not solve the badly planner points positioning problematic nor does it discourage such bad planning practices.  Good planning practice should so encourage: Do NOT (never) click to near to the road junctions. 
Remark: Some small sideroads available in the routing data can even be hidden by the visible map not displaying them.

**Comment by nrenner** [comment] 2022-05-24 19:08
Probably also related regarding the wrong turn instruction near/at junction: #282

**Comment by polyscias** [comment] 2022-05-24 19:46
Yes, agreed the turnInstructionCatchingRange does not what it is supposed to do.

Looking at the details and past experience I think one possible solution here is to make the extend algorithm that snaps the via point to the line structure to check if there is a crossing nearby and if so, snap to that instead of the point closest on the way. This will also be good for other purposes.

I added some debug code to [VoiceHintProcessor.java](https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/VoiceHintProcessor.java) and that reveals the likely problem: 

The voice instructions are generated in two steps, first from _to_ to _via1_ and then from _via1_ to _to_

That can explain a big part of the strange behavior I think and is not what is wanted I think.

**Comment by afischerdev** [comment] 2022-05-25 14:14
We have a turnInstructionCatchingRange problem, yes. I'm with @polyscias some thing with an additional snap logic seems to be a good idea.
But where is the break between snapping to junction or way?
2,5,10,20 meters?
And how to know if this peak from the main way is intended or just a bad mouse click?

When you have short view on [this ](https://bikerouter.de/#map=17/51.06124/13.76679/standard&lonlats=13.764484,51.06054;13.768111,51.061641;13.766512,51.061725). It is off a catching range. But it shows the voicehint problem. All gpx exports with voicehints as wpts meets the turn point  13.766777,51.061312 twice, on the way to u-turn point and back to river. Only the second one is valid. Please try the index based export 'comment-style' or json export - BRouter calculates it well.
Btw. export 'auto-choose' = 1 has a index based gpx variante that covers a little bit of [issue #499](https://github.com/nrenner/brouter-web/issues/499) - voicehints at the trkpt - but is not reachable on BRouter server.


For more turnInstructionCatchingRange discussion please see #375
There are a lot of tests for critical voicehints.
Use this branch for [testing](https://github.com/afischerdev/brouter/tree/voicehint-problem).
It uses a turnInstructionCatchingRange of 2 meters and that covers a lot of the problems. 
We also played a little bit with the turning angles.
So please have a critical look on it.

Coming back to start: U-turn command missing
All this doesn't effect the main request. 
If we want it in this sketched situation, we should try to add it.

**Comment by polyscias** [comment] 2022-05-25 18:43
> some thing with an additional snap logic seems to be a good idea.
> But where is the break between snapping to junction or way?

On the snapping logic, and far as I understand it now, the problem is only there only for via points and if there is a crossing nearby, no problem when there is only a way. 

A workable solution is I think to look for a crossing that is within say 10 meter and it is present, take it. If the waypoint is further away from a line, take the normal perpendicular line and check if along the way within 10 meter a crossing is and if so, that that.

The "10" meter could maybe be the same numbers as the turnInstructionCatchingRange

The other problem that should be solved I think before further improvements is not to have the voice instructions for routes with via points not generated in a step per segment, i.e. first from to to via1 and then from via1 to to. Instead the voice instructions should be calculated for the whole track in one go.

**Comment by afischerdev** [comment] 2022-05-31 07:58
> A workable solution is I think to look for a crossing that is within say 10 meter and it is present, take it. If the waypoint is further away from a line, take the normal perpendicular line and check if along the way within 10 meter a crossing is and if so, that that.

My name on this problem is 'avoid peaks'. This means not to have a view on only one point. A 'peak' can have more points. I have a workaround on that, but I can't 'deliver' now - or the next days, hope on next week.
The Idea is to walk back the line and rearrange current and previous segment when the points are equal.


> the voice instructions should be calculated for the whole track in one go.

I agree that. It could be saved several of the discussed problems. This is on agenda as well as other ideas.

**Comment by 0709wiwiwi** [comment] 2022-05-31 09:51
@afischerdev
You must ensure that the planner operator remains free to keep the planned U-turns.
It is only up to the planner operator to decide whether or not he wants the U-turn to be kept.

**Comment by nrenner** [comment] 2022-06-01 08:59
> The Idea is to walk back the line and rearrange current and previous segment when the points are equal.

>>    the voice instructions should be calculated for the whole track in one go.

I think this would break a basic principle of consistent results between routing individual segments and the whole route, which is what brouter-web relies on, don't know about other clients.

Don't know about all the implications and pros and cons, and might be Ok for just voice hints, but such a potentially breaking change should be given some consideration.

**Comment by afischerdev** [comment] 2022-06-01 20:29
@nrenner 
Yes, I think we have to view this very carefully.

As far as I know the web client connects segment by segment. This will work as normal, only with more then two points in lonlats new function is active.

**Comment by 0709wiwiwi** [comment] 2022-06-02 09:51
Just this pse.  Github/abrensch/brouter) (app/engine) 
**The simple request is**:  Please generate the (180°) U-turn command.
(_That by U-turns you fastly notice possible trackglitches is a nice extra_) 

https://forum.kurviger.de/t/app-improve-brouter-turn-instructions/3143/8?u=0709
_Quote: 
The turn instructions should be generated by the routing engines,
which know the road segments & traffic rules at each route point_.

**Comment by nrenner** [comment] 2022-06-02 19:43
> As far as I know the web client connects segment by segment. This will work as normal, only with more then two points in lonlats new function is active.

The upcoming brouter-web release switches export from re-requesting the whole route with all points to concatenating client-side segments, so it won't be affected but also won't benefit from those changes. And results would then be different from the app, which isn't ideal.

But I will open a separate issue for that discussion.

> Just this pse. Github/abrensch/brouter) (app/engine)

Core results from app/engine and web should be consistent.

> The simple request is: Please generate the (180°) U-turn command.

Currently the router processes each segment between two route points separately, **and I guess this is on purpose**, so it can't detect those U-turns.

Changing that to looking at the whole route would be a fundamental breaking change that might have unintended consequences, so I think it needs to be discussed and well-considered.

**Comment by 0709wiwiwi** [comment] 2022-06-03 06:14
@nrenner.  Hello Norbert.
"So it can't detect those U-turns".
As far as the lack of U-turns is concerned, this is still a BRouter shortcoming for me. 
An example of a (now) good U-turn usage can be found here. 
https://forum.kurviger.de/t/app-turn-instructions-on-waypoints/4300
Just see how very misleading the turn instruction sequences are without the U-turn command. 
Without that U-turn message you even used to continue your drive here until the off track signal than came.

The Kurviger app now indeed uses the (GH) engine U-turn signal to its full potential.

Also if apps, when driving wrong, by auto recalculation, it would also be useful to get the U-turn command instead of that very misleading (180°) straight ahead. Commercial (car) GPS systems will sure of course ask you to turn around, and if you still drive on, than an alternative proposal follows. With Locus_Brouter this alternative design comes after the second recalculation. Method proposal triggered by @poutnikl in Locus.

@poutnikl  Hello Libor.
I once reported strange BRouter turn instructions followed by the comment that it was technically impossible to do otherwise.
Note that the erroneous BRouter turn instructions reported then are now correct. That reported issue was so nicely solved in silence after all. To optimise routing results, you should first report the usage problem. Of course.

**Comment by poutnikl** [comment] 2022-06-03 08:01
@0709wiwiwi  To clarify, I had no problem with that myself, as I understood there was a Brouter backend layer and the (web/android) application frontend layer and how they (may) approach routes and route segments. 

Personally, I am not so much lately interested in the web application, preferring LocusMap route planner.

**Comment by 0709wiwiwi** [comment] 2022-06-04 07:23
@poutnikl.
Roger, sure plenty of choice. I prefer Brouter web. What's missing is U-turn & Shaping & Via Points in the gpx export.
The excellent combination of both Shaping & Via Points by (GH) Kurviger makes this app powerful and user-friendly.
As a result the Kurviger app so surpasses some navigation gps apps in terms of flexible friendly **track navigation.**
A gps app should also perform very well offline, so it is necessary to continue to improve the BRouter (app) as well.
This includes, when offtrack, faster alternative recalculation results through the BRouter app. However, that's a separate story.

**Comment by afischerdev** [comment] 2022-06-08 08:44
> Changing that to looking at the whole route would be a fundamental breaking change that might have unintended consequences, so I think it needs to be discussed and well-considered.

Yes, I think so. 

@nrenner 
Could you please tell us - I don't know enough about the history - why the web client 'only' uses single segment requests? 

I had a look on your wiki 'segments vs. full route'.
- One reason is the use of direct routing. But there was already in older versions of BRouter server a part on beeline routing. And a [new one](https://github.com/nrenner/brouter-web/pull/497#issuecomment-1136054976) as well.
- 'different route' I can't follow. Always get correct route (with / without extra points)
- 'no height on bridge' Interesting, I didn't get a height in this example either, but it has nothing to do with multi or single segment for me.
- 'turn instruction when via point is exactly on junction node' should be done with the update

And we have some bothering routing instructions through single segment requests. Is that the reason why we don't see voice hints on web client?

**Comment by afischerdev** [comment] 2022-06-08 09:37
Now I can publish a work around.
The idea is to go back the line when points on prev track and new track are equal.
And the voicehint generation is moved from track by track to the end - with detours. 
Time and energy are calculated back but differ a bit to a plain track.

You find it on [afischerdev/avoid-peaks](https://github.com/afischerdev/brouter/tree/avoid-peaks)

There are some new rules:
- With parameter 'avoidPeaks=1' you can switch on/off the new logic.
- Additional the parameter 'avoidPeaksDistance=60' sets a break distance for catching a peak. Default is 'avoidPeaksDistance=0', means no distance check.
- When a peak has a poi around, peak is not dropped. 

This can not be tested with web client so here are some wget samples:

```
wget  -O result_1.gpx "localhost:7777/brouter?lonlats=13.764484,51.06054|13.767552,51.061545|13.766512,51.06172&profile=trekking&alternativeidx=0&turnInstructionMode=1&profile:avoidPeaks=1"

wget  -O result_2.gpx "localhost:7777/brouter?lonlats=13.764484,51.06054|13.767552,51.061545|13.766512,51.06172&profile=trekking&alternativeidx=0&turnInstructionMode=1&profile:avoidPeaks=1&profile:avoidPeaksDistance=30"

wget  -O result_3.gpx "localhost:7777/brouter?lonlats=13.764484,51.06054|13.767552,51.061545|13.766512,51.06172&profile=trekking&alternativeidx=0&turnInstructionMode=1&profile:avoidPeaks=1&pois=13.767423,51.061584,Restaurant"

```

turnInstructionMode == 1 is now reachable in export and contains voicehints information on trackpoint.

avoidPeaks should be found in the editable part of the profiles. So user can play around with it.

This is not ready and needs a carefully test.

**Comment by 0709wiwiwi** [comment] 2022-06-14 15:06
You can see how you sometimes unexpectedly produce those very annoying trackglitches in the sample video here.
https://www.mtb-news.de/forum/t/brouter-web-fragen-antworten-hilfe-profile-tipps-etc.917910/post-18064906
![Trackglitch](https://user-images.githubusercontent.com/54167201/173610852-06ab425e-02c8-4fc3-b62e-c55bb320e16d.png)

I produced a similar short design based on that demo video:  https://t.ly/yBs_

This is a short track, you hardly will notice trackglitches on longer tracks with a zoomed out map.
Attached find a gpx track with instructions in trackpoints inclusive the U-turn and the unexpected turn instructions.
The original trigger planner waypoints are only "for illustration purpose" also added here.
The trigger planner waypoints are "snapped" into a Via or Shaping trackpoint indicated by the sym pass_place.

[Gräbendorf -_ Dolgenbrodt (8km)_navtrkpt_wpt.gpx.txt](https://github.com/abrensch/brouter/files/8900966/Grabendorf.-_.Dolgenbrodt.8km._navtrkpt_wpt.gpx.txt)

**Comment by afischerdev** [comment] 2022-06-15 16:03
@0709wiwiwi 
For your sample I merged the direct line logic into the  [avoid-peaks](https://github.com/afischerdev/brouter/tree/avoid-peaks) branch. Was introduced [here](https://github.com/nrenner/brouter-web/pull/497#issuecomment-1136054976) - see for more info.

With this you can switch between direct lines or not in server and you get this results (Locus new export with reduced name tag, you asked for in #332):

[testtrack0.avoid-peaks.gpx.txt](https://github.com/abrensch/brouter/files/8910934/testtrack0.avoid-peaks.gpx.txt)

[testtrack0.direct.gpx.txt](https://github.com/abrensch/brouter/files/8910939/testtrack0.direct.gpx.txt)

At the moment only available for the server variante, Android will follow.

**Comment by 0709wiwiwi** [comment] 2022-06-15 17:48
@polyscias 
Nice, the turnpoints are sure perfectly fucntional with the gpx track import.

By the way I can't of course not forbid anyone to use the name tag though. 
But you might understand why I prefer to keep the name tag free at turnpoints.
This is necessary to compactly apply announced ViaPoint_U-turn combinations in the gpx trackfile. 

What I don't see in the export gpx trackfile yet are the "snapped" planner trackpoint positions.
Planner points 'snapped' to a trackpoint to be tagged with 'sym' pass_place & 'type' Via.
Locus map actual already uses these positions as perfectly reusable Via points. 
Whether you then automatically or manually assign a name or not is completely free.
At navigation a Via trackpoint without a name is of course without TTS announcement. 
Anyway such a Via trackpoint is shown in the turnlist and as Via Icon in the app.
(Not announced Shaping points should NOT be shown nor in the turnlist nor as Icons)

See a question about the possible recovery of the planning Via points (Shaping) in a gpx track file.
https://www.mtb-news.de/forum/t/brouter-web-fragen-antworten-hilfe-profile-tipps-etc.917910/post-17690773

Thank you anyway for your enthusiasm and fast development progress.

**Comment by 0709wiwiwi** [comment] 2022-06-15 21:05
@[afischerdev](https://github.com/afischerdev)

I have thought a bit more about the new "avoid¨Peak" tool which you propose and introduces.
With parameter 'avoidPeaks=1' you can switch on/off the new logic or else you apply avoidPeaksDistance=0 or 60 or 10 etc.  
. 
What would you think of the following ? 

- For not announced Shaping Points which cause a U-turn the avoidPeak tool works.
(I expect that 90 % of the planner points are thus not announced Shaping Points)
- At the announced Via Points which cause a U-turn the avoidPeak tool is ignored.

If you produce U-turns due to a (too) quickly placed Shaping Point the avoidPeaks tool will intervene according to the profile setting.
If you do want to set a U-turn, even if it is in the catching range of the avoidPeaks tool, you need to produce it with a Via Point. 
The placement of a U-turn is then by no means still an accidental mistake, but it is so clearly a real planned one.

**Comment by 0709wiwiwi** [comment] 2022-06-16 12:43
https://github.com/nrenner/brouter-web/issues/498

How to promote route points to Via points without extra button in the BRouter web GUI ?
The construction of a new route is by quickly placing route (reference) Planner Points without a name.
So from the Start (automatic name to Via) so on with tap tap tap this until the End (automatic name Via).
These quickly placed route planner points without a name can so be considered as Shaping  points.
You could promote some to be announced Via points in the navigation by giving them a name.
Name edit trigger by right-clicking or long-clicking on the Planner point on touch screens.

**Comment by afischerdev** [comment] 2022-06-17 16:24
@0709wiwiwi 
>Locus map actual already uses these positions as reusable Via points.
Interesting feature - did not know that before. Good point on continues routing when you miss the route.
So I add this to Locus export. 

[testtrack0.via.gpx.txt](https://github.com/abrensch/brouter/files/8929080/testtrack0.via.gpx.txt)

> You could promote some to be announced Via points in the navigation by giving them a name.
Name edit trigger by right-clicking or long-clicking on the Planner point on touch screens.

Good idea, I think this could work.

**Comment by 0709wiwiwi** [comment] 2022-06-17 20:50
Yes, this Via trackpoint import works fine as expected in Locus folder.

Start and End trackpoints automatically with 'name' are with 'type' Via.
Middle planner points without 'name' are preferably with 'type' Shaping.
Only when you add a 'name' in the Brouter planner, then with 'type' Via.

I try to preserve the simple Brouter operation in this way.
The BRouter gpx export file is so functional and basic simple.

With gpx editor or Notepad++ you can always change the 'type' with or without a 'name'.
In the Locus planner you can convert imported Via points to Shaping Points.
In the Kurviger and Cruiser app, this is even easier and quicker to convert.
Kurviger and Cruiser support gpx 'type' Via or Shaping in gpx (rte) routes.

Translated with www.DeepL.com/Translator (free version)

**Comment by 0709wiwiwi** [comment] 2022-06-18 06:29
@[afischerdev](https://github.com/afischerdev)

I am curious about the effectiveness of the "avoid Peak tool.
Find here attached a nice gpx (rte) route file to test it now.
[TET_0.50km_rte_ticks_type_shaping.gpx.txt](https://github.com/abrensch/brouter/files/8933065/TET_0.50km_rte_ticks_type_shaping.gpx.txt)
Calculate by the gpx (rte)route import, weird, in Brouter menu import as track ;-)
_(The Kurviger_Cruiser app import by wpt&rte&trk menu is perfectly clear though)_
Set Profile Trekking Bike & use default fuziness, so using all routepoints.
Normally you find a single Peak over the total traject (km22).
With set avoidPeaksDistance=30 the result is without peak ?

**Comment by afischerdev** [comment] 2022-06-19 16:23
> Middle planner points without 'name' are preferably with 'type' Shaping.

I've changed this. 
And I enabled: a name on a match point and point is ignored for 'avoid peaks'.

[testtrack0.via_new.gpx.txt](https://github.com/abrensch/brouter/files/8933931/testtrack0.via_new.gpx.txt)

> With set avoidPeaksDistance=30 the result is without peak ?

Yes, I can confirm the peak is inside 30 meters and removed.
And when you use the a new BRouter app, Cruiser will route the import gpx without peaks.

**Comment by 0709wiwiwi** [comment] 2022-06-19 19:18
Excellent message.
Anyway I do have one more question.
Why does trkpt14 generate a U-turn_right and not a simple U-turn ?  

U-turns. The difference.
- A (180°) U-turn returns by exactly using the same way. Triggered by a Planner Point. Suspicious ! 
(This is the type of U-turn where you have to be a bit alert all the time)
- A left U-turn is a normal  turn where you return over a parallel lane. Not triggered by a Plannerpoint. Not suspicious. 
- A right U-turn is a normal turn where you return over a parallel carriageway. Not triggered by a Plannerpoint. Not suspicious. 

Following examples are to be generated **by the Profile Car (fast) !**
Find the shortlink to BRouter web in the gpx file.
Gpx tracks with a U-turn left as generated by BRouter.
See the gpx tracks with the instructions in track points.
[1_Lokeren_navtrkpt_(0.7km).gpx.txt](https://github.com/abrensch/brouter/files/8936220/1_Lokeren_navtrkpt_.0.7km.gpx.txt)
[2_Zele (0.2km).gpx.txt](https://github.com/abrensch/brouter/files/8936221/2_Zele.0.2km.gpx.txt)

Note.
Actual BRouter Locus gpx track & waypoints (extension) export.
The actual BRouter generates 2 of the 3 possible U-turns. 
- Generates the directional U-turn left and U-turn right.
- Does NOT generate the non-directional (180°) U-turn.

BRouter Locus rtepointAction.
1. The simple U-turn command by rtepointaction 12. 
Icon is simple inverted U. (Not yet in Locus)
2. The left U-turn by rtepointaction 13. 
Icon is an inverted U with a small arrow pointing to the left.
3. The right U-turn by rtepointaction 14. 
Icon is an inverted U with a small arrow pointing to the right.

Information. (compare).

_GraphHopper generates all 3 U-turn versions.  
The GraphHopper signs:
1. The simple U-turn command by GH sign:(-98). 
Icon is a simple inverted U. (Icon in Kurviger)
2. The Left U-Turn by GH sign: (-8). 
Icon is an inverted U with a small arrow pointing to the left.
3. The right U-turn by GH sign (8). 
Icon is inverted U with a small arrow pointing to the right._

![Kurviger U turns](https://user-images.githubusercontent.com/54167201/174496814-829c273f-0731-4c23-9cd8-fe0cb2dccb29.png)

**Comment by 0709wiwiwi** [comment] 2022-06-20 05:33
Why that strange "U-turn_right" ?  (Very rare on EU mainland). 
Maybe is caused by the "turnInstructionCatchingRange" ?
The "U-turn" and next "stay_right" possibly results in "U-turn_right" ?
https://github.com/abrensch/brouter/issues/332#issuecomment-1150809786
**To test:** removal of the turnInstructionCatchingRange rule.

**Comment by 0709wiwiwi** [comment] 2022-06-21 14:18
GH web result with U-turn here.
https://t.ly/gfT-

A remarkable difference between the track export by GH and BRouter.

https://t.ly/NQkE9

The U-turns by Brouter are perfect 180° returns. (No 179, no 181).
The Locus map app planner has a track glitch detector, but no cure.
This Locus map tool only indicates, the user must correct himself.

The difference with this new implementation is that you detect AND heal automatically.
The user retains full control because the set conditions for auto healing are simply defined. 
Only auto intervenes with the (fastly) placed Planner Points (Shaping without name) within a set "capture distance". 

**I find this ultimately more convenient and faster than just the 'marking' in Locus map.**

_I'm not an osmand user, but I do notice in their forums that this problem is also a frequent occurrence there.  To avoid trackglitches, however, you need to notice them first.  Imo generating U-turns and paying attention to the undesired ones also would lead to a more optimal track production in the osmand app._

**Comment by 0709wiwiwi** [comment] 2022-06-28 08:01
"avoid-peaks".

I did read the comment of @zod
Notice I did use "trackglitch detector".
Detector, because is not a "curing" tool.

Suggested is a tool to avoid the creation of "trackglitches".
Tracks (trk) can have annoying glitches, routes (rte) not.
A track used to be navigated technically still remains a track (trk) !

[NL] https://www.javawa.nl/unglitcher.html.
The "unglitcher".
Avoids confusion, users do call tracks also (non technically) routes.

[NL] https://help.routeyou.com/nl/topic/view/37/track
Begripsverwarring
Eenmaal een track opgeladen is bij RouteYou spreken we bij RouteYou over een route (in de RouteYou betekenis).
Dit is dus een andere betekenis dan wat men aan dat begrip geeft in de GPX (topografix)_Garmin wereld.

**Comment by nrenner** [comment] 2022-07-01 16:06
> Video demo: https://youtu.be/rIirfld57lc
> This is why I ask U-turn and instructions in trkpt support.

Manually scanning the list of turn instructions for u-turns, as a possible hint for glitches, isn't an ideal solution in my opinion.

Missing u-turn instructions are not the problem here. The problem are unintended back and forth detours (peaks/glitches/spikes) that go unnoticed by the user.

From a client-side perspective, the most obvious solution for me would be to warn the user about such a peak right at the moment it occurs, e.g. by placing a warnig sign in the via marker. The user can then manually check and fix the problem while editing the route and before exporting. Very much like your ["alert signal" proposal](https://github.com/abrensch/brouter/issues/436#issuecomment-1137724508) above:

![peak warning](https://user-images.githubusercontent.com/54167201/170952421-294e800a-9cd7-4951-8d4e-5c10fd209b64.gif)

The client should be able to detect such peaks when two neighbouring segments are joined by more than one common track point. No u-turn voice hints needed for that.

**Comment by poutnikl** [comment] 2022-07-01 16:10
I cannot imagine I would plan a multiday trip or expedition without viapoints/Shapepoints, at least for important POIs or camps(whatever is meant by that). And more probably, I would make separated daily routes. GH comparison is an underbelt hit, as GH uses AFAIK  https://en.wikipedia.org/wiki/Contraction_hierarchies , an algorithm specialized for long distances, using intensively preprocessed data.

**Comment by nrenner** [comment] 2022-07-04 14:47
> The 180° U-turn indication is a Kurviger proposal that has not yet been realised.

The idea was to maybe implement something similar in BRouter-Web.

Your comment above sounds like the BRouter-Web client isn't involved at all - do you actually use that? 

Just trying to understand the use cases and what that all means for BRouter-Web, and if we have a theoretical or practial consistency issue here.

**Comment by 0709wiwiwi** [comment] 2022-07-04 17:13
Right. 

This entry was moved (advised) from Brouter web nrenner to BRouter abrensch.

Generator.
The U-turn command generation is in the **Brouter engine abrensch.** Job done.

Web planner.
The U-turn warn signal is expected in the **BRouter web client nrenner**.
The operator planner than accepts or ignores the visual U-turn signal. 

App planner(s).
Apps are also clients with which you can plan additionally or totally new. The app dev decides whether to apply a U-turn warning or not in the route planner display. (Locus_Brouter does by a 180° return track detect)

**Closed** 2023-04-27 12:04 UTC
